### ISSUE TITLE
check if state legs have left office and update accordingly 

### ISSUE THREAD

**Issue by meganrm** [townhallproject/lawmakers-manager#8]

**Comment by meganrm** [comment]
need to make sure to not override manual edits

**Comment by JacksonMaxfield** [comment]
Thinking out loud: I assume we would just turn the update script into a cron job and in the case of manual edits could we also include a key that simply says `"editedManually": true` and when the update script runs, anything that isn't marked as such will run.

I guess I should ask, how are the MoC's manually edited? Is it through a web ui? Through the firebase ui? If a web ui this becomes an easy task, if through firebase ui its still easy but more time consuming.

**Comment by JacksonMaxfield** [comment]
This is solved by the switch to firestore branch in how it actually manipulates the data. It assumes that whatever is in the database is correct but will update with any new information.
